version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: Exam 
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Passord01
    ports:
    - '5432:5432'
    volumes:
    - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local